//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfDivanXD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Zakazi1 = new HashSet<Zakazi>();
        }
    
        public int Код_клиента { get; set; }
        public Nullable<int> Код_заказа { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчесто { get; set; }
        public string Телефон { get; set; }
        public string Адресс { get; set; }
    
        public virtual Zakazi Zakazi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazi> Zakazi1 { get; set; }
    }
}
