//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfDivanXD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakazi()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int Код_заказа { get; set; }
        public int Код_товара { get; set; }
        public int Код_доставки { get; set; }
        public int Код_клиета { get; set; }
        public string Адресс_доставки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Clients Clients1 { get; set; }
        public virtual Dostavka Dostavka { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
